name: publish-web-webhook

on:
  push:
    tags:
      - web-webhook-v*

env:
  PROJECT-DIRECTORY: src/Web/KaiheilaSharp.Web.Webhook
  DOTNET-VERSION: 6.0.x

jobs:
  publish-to-nuget:
    if: "!contains(github.event.head_commit.message, 'skip-ci') || startsWith(github.ref, 'refs/tags/')"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set version
        id: setup_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/web-webhook-v/}

      - name: Setup .NET ${{ env.DOTNET-VERSION }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET-VERSION }}

      - name: Install dependencies
        working-directory: ${{ nv.PROJECT-DIRECTORY }}
        run: dotnet restore

      - name: Build
        working-directory: ${{ env.PROJECT-DIRECTORY }}
        run: dotnet build --configuration Release --no-restore

      - name: Pack
        working-directory: ${{ env.PROJECT-DIRECTORY }}
        run: dotnet pack KaiheilaSharp.Web.Webhook.csproj -c Release -o ./dist -p:Version=${{ steps.setup_version.outputs.VERSION }}

      - name: Publish
        working-directory: ${{ env.PROJECT-DIRECTORY }}
        run: dotnet nuget push dist/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
    